[book]
authors  = ["Arbiter Contributors"]
language = "en"
src      = "docs"
title    = "Arbiter Documentation"


[output.html]
default-theme        = "dark"
git-repository-url   = "https://github.com/harnesslabs/arbiter"
preferred-dark-theme = "ayu"
site-url             = "https://arbiter.harnesslabs.dev"
