[book]
authors      = ["Arbiter Contributors"]
language     = "en"
multilingual = false
src          = "docs/src"
title        = "Arbiter Documentation"


[output.html]
katex = true

[preprocessor.katex]
after = ["links"]
# KaTeX options.
error-color        = "#cc0000"
fleqn              = false
leqno              = false
max-expand         = 1000
max-size           = "Infinity"
min-rule-thickness = -1.0
output             = "html"
throw-on-error     = true
trust              = false
# Extra options.
block-delimiter  = { left = "$$", right = "$$" }
include-src      = false
inline-delimiter = { left = "$", right = "$" }
no-css           = false

[output.linkcheck]
follow-web-links = false
optional         = true
