[workspace]
exclude  = ["benches", "docs"]
members  = ["arbiter", "arbiter-core", "docs"]
resolver = "2"

[profile.release]
codegen-units = 1
lto           = true

[workspace.dependencies]
# Local
arbiter-core = { path = "arbiter-core" }

# Shared
tokio = { version = "1.49", default-features = false, features = [
  "sync",
  "rt",
  "macros",
] }
