[package]
authors = ["Harness Labs"]
description = "Core functionality for the Arbiter framework."
edition = "2021"
keywords = [
    "ethereum",
    "evm",
    "emulator",
    "testing",
    "smart-contracts",
    "multi-agent",
    "framework",
]
license = "AGPL-3.0"
name = "arbiter-core"
version = "0.11.0"
