[package]
authors = ["Harness Labs"]
edition = "2021"
name    = "arbiter-core"
version = "0.1.0"

[dependencies]
crossbeam-channel = "0.5"

# Async
async-trait.workspace = true
futures.workspace     = true
tokio                 = { workspace = true, features = ["macros", "sync", "rt"] }

# Error and logging

tracing.workspace = true

[dev-dependencies]
arbiter-macros = { workspace = true }
tokio          = { workspace = true, features = ["macros", "full"] }
tracing-test   = { workspace = true }
