[package]
build   = "build.rs"
edition = "2021"
name    = "docs"
publish = false
version = "0.0.1"

[build-dependencies]
skeptic = "0.13.7"
tokio   = { workspace = true }

[dev-dependencies]
arbiter-core.workspace    = true
revm-primitives.workspace = true
skeptic                   = "0.13.7"
